name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install protoc
      run: sudo apt install -y protobuf-compiler

    - name: Install the Go protocol buffers plugin
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

    - name: Generate protobuf files
      run: protoc --go_out=. --go_opt=paths=source_relative pb/addressbook.proto

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -covermode=atomic -shuffle=on -coverprofile=coverage.out -v ./...
